spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/glidb
    username: ######
    password: ######
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
          format_sql: true
    show-sql: true
